"""empty message

Revision ID: 90d8f142b918
Revises: ec5732dd8f95
Create Date: 2021-02-17 14:14:05.167927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90d8f142b918'
down_revision = 'ec5732dd8f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_pwd', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('use_gravatar', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['token_pwd'])
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', mysql.VARCHAR(length=512), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'use_gravatar')
    op.drop_column('users', 'token_pwd')
    # ### end Alembic commands ###
